### ISSUE TITLE
Is there a way to modify currentUser?

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#8]
Currently currentUser is established/maintained by react-devise. currentUser, has the first and last name fields which I would like to allow the user to modify with a Profile#Edit type of view.

Given that react-devise handles currentUser and I don't have access to it's reducer/actions, is there a react/redux friendly way to update currentUser in the store?

Thanks

**Comment by timscott** [comment]
You would not want to update the `currentUser` in the store.

If you only want to control how `currentUser` is composed from the user model, you can do that [in your user model's `jwt_payload` method](https://github.com/timscott/react-devise-sample/blob/master/app/models/user.rb#L9-L16).

However, I think you're asking how to edit a user. Classic Devise provides that via `registrations/edit` view, which we do not yet provide out of the box. That said, you can pretty easily build it yourself. You would create a view to edit the current user, just as you would to edit any other model. You could create your own controller and route, but it would be better to use the Devise's built-in `registrations#update` route. Based on server mods you've already made, that route will accept a JSON post.

**Comment by timscott** [comment]
There's another complication that just occurred to me. After your post to `registrations#update` the `currentUser` might not reflect that change.  You could just force the user to log back in, but that's obviously not ideal. 

You need to somehow get an updated  `authToken`. Once you do,  you can reset the `currentUser` like so:

```js
dispatch({
  type: 'LOGGED_IN',
  payload: authToken
});
```
 
You can customize `RegistrationsController#update` to return it.  Perhaps `devise-jwt` handles this in some idiomatic way.

Sorry for the vague answer. I will probably have to tackle this myself in the coming weeks.

**Comment by bhellman1** [comment]
Thanks Tim, I should have been more specific. Updating the user record on Rails is no problem... The problem is what you mentioned in your 2nd reply. To be more specific with the use case for future readers.

In my app, I created a EditProfile page that is intended to allow the user to set their first_name, last_name and photo. It's fairly easy to submit those fields to Rails and have Rails update the user record.

The challenge is, after Rails updates user, how to then tell my React app (powered by react-devise). to update store.currentUser with the updated fields without requiring a page refresh etc...

Since the currentUser's actions and reducers are inaccessible as they are baked into react-devise, I'm update to update currentUser in my app's store.

For now, I'm thinking about adding store.profile and duplicating the user profile info there (name, image, etc...) not idea but hopefully it will work. I'll then also need to update the react-devise sample app header to user store.profile vs store.currentUser

**Comment by timscott** [comment]
Gotcha. The "correct" way would be to get a authToken from the call to update the user, which you can use to reset the currentUser, as I described above. Otherwise you'll have inconsistent state, which could lead to obscure bugs.

I'm not sure how to do that off the top of my head. I'll try to investigate in the coming days. This must be a common issue with jwt auth, since jwt tokens hold user info be design. So there must be some idiomatic solution.

**Comment by timscott** [comment]
FTI - I submitted [an issue](https://github.com/waiting-for-dev/devise-jwt/issues/21#issuecomment-310977595) to `devise-jwt` relating to this. You might find it helpful to follow. I will plan to look into this a little further in the coming days.

**Comment by timscott** [comment]
Check out the conversation in the [aforementioned `devise-jwt` issue](https://github.com/waiting-for-dev/devise-jwt/issues/21#issuecomment-310977595).

The token can be refreshed by tweaking the config like so:

```ruby
config.jwt do |jwt|
  # other config
  jwt.dispatch_requests = [
    ['PATCH', %r{^/auth$}] # This is the route to registrations#update. Change it according to the route you are using the update the current user.
  ]
end
```

And then upon a successful user update, grab the token from the Authorization header and replace the existing one, thus updating `currentUser`:

```js
dispatch({
  type: 'LOGGED_IN',
  payload: authToken
});
```

DISCLAIMER: Please read the [issue](https://github.com/waiting-for-dev/devise-jwt/issues/21#issuecomment-310977595) mentioned above which has some info an advice about practices with JWTs. You might want to consider NOT putting user related info into the token. Also, the code above does not revoke the old token, which also might NOT be a best practice.

**Comment by bhellman1** [comment]
Thanks Tim, I appreciate the update.. If I'm understanding the threads correctly, are you saying updating the currentUser is now supported by react-devise? Or do you still this feature being added in a future update of react-devise?

**Comment by timscott** [comment]
The way to update `currentUser` in the store with is:

```js
dispatch({
  type: 'LOGGED_IN',
  payload: authToken
});
```

So you need to get a fresh token from the server. You should not ever mutate `currentUser` without a fresh token.

`react-devise` does not yet provide a form or action for the `registrations#update` route, so you have to roll that yourself. We might add this at some point. It's probably not a high priority since in the typical case the form would need to created custom anyway, so as to include user attributes that are not related to authentication (e.g., first_name, last_name, etc).

`react-devise` does not strictly depend on `devise-jwt`, but that's what we use in the sample app and how-to docs. It does not by default return a fresh auth token (jwt) from the call to `registrations#update`. So you have to configure that as described in this issue and the referenced issue.

We might at some point create a Rails gem that will handle server setup, which likely will depend on `devise-jwt`. We would likely provide behavior, possibly via configuration, that would handle this on the server side.

**Comment by bhellman1** [comment]
Thanks again. I ended up deciding to move **all** user info outside of currentUser.

**Comment by timscott** [comment]
Might not be a bad idea. That's essentially what the maintainer of `devise-jwt` recommended, not to put volitile user info into JWT tokens.
